#name = "helloworld-worker"
#type = "javascript"
#
## 指定 Worker 入口
#route = "/helloworld"  # 你希望这个 Worker 处理的路径
#workers_dev = true      # 开启本地开发模式（可以在本地测试）
#
#[build]
#command = "npm run build"  # 构建命令，如果是 Vue 或其他前端框架，通常是 `npm run build`
#upload = { dir = "dist", format = "modules" }
#
#
##[env.production]
##main = "functions/customer.js"  # 指定 Worker 脚本的入口
#
## 依赖项配置
#[build.upload]
#format = "modules"          # 使用ES模块格式
#module_rules = [
#    { type = "ESModule", globs = ["**/*.js"] }
#]