name = "helloworld-worker"
type = "javascript"

# 指定 Worker 入口
route = "/public"  # 你希望这个 Worker 处理的路径
workers_dev = true      # 开启本地开发模式（可以在本地测试）

[build]
command = "npm run build"  # 构建命令，如果是 Vue 或其他前端框架，通常是 `npm run build`

[build.upload]
dir = "dist"  # 要上传的目录
format = "modules"  # 使用 ES Modules 格式
module_rules = [
    { type = "ESModule", globs = ["**/*.js"] }
]

[env]
main = "global_main"

[env.production]
main = "prod_main"  # 指定 Worker 脚本的入口

[env.dev]
main = "dev_main"  # 指定 Worker 脚本的入口
