name = "helloworld-worker"
workers_dev = true      # 开启本地开发模式（可以在本地测试）

# 指定 Worker 脚本入口点
main = "functions/public.js"  # 这里指定 Worker 脚本的入口文件

compatibility_date = "2025-03-26"  # 兼容性日期，必须设置

[assets]
directory = "./dist"  # 如果有构建出来的静态文件，指定目录

[env]
main = "functions/public.js"  # 开发环境下 Worker 脚本的入口

[env.production]
main = "functions/public.js"  # 生产环境下 Worker 脚本的入口

[env.dev]
main = "functions/public.js"  # 开发环境 Worker 脚本的入口